apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: locust-es01
  name: locust-es01
  namespace: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-es01
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: locust-es01
    spec:
      containers:
      - image: locust-es01:tag01
        imagePullPolicy: Always
        name: locust
      dnsPolicy: ClusterFirst
